name: Stock Screener

on:
  schedule:
    - cron: '30 6 * * 1-5'  # 每个工作日 14:30 (北京时间)运行
  workflow_dispatch:  # 允许手动触发

jobs:
  screen:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install akshare
        pip install pandas
        pip install flask
        pip install flask-cors
        
    - name: Run stock screener
      run: |
        mkdir -p logs
        python src/main.py > logs/stock_screener.log 2>&1
        
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: stock-screener-logs
        path: logs/stock_screener.log