name: Stock Screener

on:
  schedule:
    - cron: '30 6 * * 1-5'  # 每个工作日 14:30 (北京时间)运行
  workflow_dispatch:  # 允许手动触发

jobs:
  screen:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install akshare==1.11.11
        pip install pandas==1.5.3
        pip install flask==2.3.3
        pip install flask-cors==4.0.0
        
    - name: Run stock screener
      run: |
        python -c "
        import akshare as ak
        import pandas as pd
        from datetime import datetime
        
        def run_screener():
            try:
                df = ak.stock_zh_a_spot_em()
                if df is not None:
                    df.to_csv('stock_data.csv', index=False)
                    print(f'数据获取成功: {len(df)} 条记录')
                else:
                    print('数据获取失败')
            except Exception as e:
                print(f'运行错误: {str(e)}')
        
        run_screener()
        "
        
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: stock-data
        path: stock_data.csv